image: debian:stable-slim

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
# Function variables
# Modify the following values to match the ones desired for your function
# Remember to modify each environment service accounts if required
  NAME: "generateSubscriptionKey"
  RUNTIME: "nodejs10"
  MEMORY: "256MB"

stages:
  - test

tester:
  stage: test
  image: node:16
  script:
    - npm install
    - npm run test

linter:
  stage: test
  image: node:16
  script:
    - npm install
    - npm run eslint
